steps:

- name: 'gcr.io/cloud-builders/git'
  id: Replace facade vars
  volumes:
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s#_CKAN_API_URL#${_CKAN_API_URL}#g" manifests/facade/facade-deployment.yaml
    sed -i "s#_FACADE_SECRET_KEY#${_FACADE_SECRET_KEY}#g" manifests/facade/facade-deployment.yaml
    sed -i "s#_CKAN_API_KEY#${_CKAN_API_KEY}#g" manifests/facade/facade-deployment.yaml

# This step only applies the managed cert for Facade in dev/test
- name: 'gcr.io/cloud-builders/git'
  id: Facade managed cert
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s#_DOMAINNAMEF#${_DOMAINNAME_FACADE}#g" manifests/facade/facade-managed-cert.yaml

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=manifests/facade/
  - --location=europe-west1
  - --namespace=${_NAMESPACE}
  - --cluster=${PROJECT_ID}-cluster
  timeout: 600s

