apiVersion: v1
kind: Service
metadata:
  name: ckan-service
  labels:
    app: ckan
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: ckan-port
    port: 5000
    targetPort: ckan-app
    protocol: TCP
  selector:
    app: ckan
