apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-configmap
data:
  ckan_init_solr.sh: |
    #!/bin/bash
    #
    # Initialize SOLR for CKAN by creating a ckan core

    set -e

    echo "Check whether SOLR is initialized for CKAN"
    CKAN_CORE_NAME=ckan
    CORESDIR=/var/solr/data

    COREDIR="$CORESDIR/$CKAN_CORE_NAME"
    if [ -d "$COREDIR" ]; then
        echo "SOLR already initialized, skipping initialization"
    else
        echo "Initializing SOLR core $CKAN_CORE_NAME for CKAN $CKAN_VERSION"
        # init script for handling an empty /var/solr
        /opt/docker-solr/scripts/init-var-solr
    
        # Precreate CKAN core
        /opt/docker-solr/scripts/precreate-core $CKAN_CORE_NAME
    
        # Replace the managed schema with CKANs schema
        echo "Adding CKAN managed schema"
        cp /config/schema/schema.solr8.xml /var/solr/data/$CKAN_CORE_NAME/conf/managed-schema
    
        echo "SOLR initialized"
    fi
